name: Generate metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: studygeorge
          template: classic
          base: header, activity, repositories
          config_timezone: America/New_York
          config_display: large

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: studygeorge
          base: ""
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          config_display: large
